trigger:
- master

pr:
- master

pool:
  name: 'selfpool'

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    name: 'selfpool'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'service'
      repository: 'azurproj'
      command: 'buildAndPush'
      Dockerfile: '/home/mansi/azuproj/Dockerfile'  # Adjust this path to point directly to your Dockerfile

  - script: |
      docker tag azurproj:$(Build.BuildId) mb2122/azurproj:latest
    displayName: 'Tag Docker Image'

- job: RunDockerContainer
  displayName: 'Run Docker Container'
  dependsOn: BuildAndPushDockerImage
  pool:
    name: 'selfpool'
  steps:
  - script: |
      docker run -d -p 8080:80 --name azurproj_container mb2122/azurproj:latest
    displayName: 'Run Docker Container'
